# Generated by Django 4.1.5 on 2023-01-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_page_created_at_page_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulol')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulol')),
                ('active', models.BooleanField(default=False, verbose_name='aktívny')),
                ('file', models.ImageField(upload_to='', verbose_name='Obrázok')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'článok', 'verbose_name_plural': 'články'},
        ),
        migrations.AddField(
            model_name='post',
            name='carousel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.carousel'),
        ),
    ]
