# Generated by Django 4.1.5 on 2023-01-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_carousel_alter_post_options_post_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tagy'),
        ),
    ]
