# Generated by Django 4.1.5 on 2023-01-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='Titulok')),
                ('text', models.CharField(max_length=255, verbose_name='Text rýchlej novinky')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='carousel',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='tagy delené čiarkou, bez symbolu # napr. turnaj, chlastačka,', max_length=255, null=True, verbose_name='Tagy'),
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
