# Generated by Django 4.1.5 on 2023-01-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_quicknew_remove_post_carousel_alter_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicknew',
            options={'verbose_name': 'rýchla novinka', 'verbose_name_plural': 'rýchle novinky'},
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='popis'),
        ),
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='kľúčové slová'),
        ),
        migrations.AddField(
            model_name='page',
            name='publised',
            field=models.BooleanField(default=True, verbose_name='publikované?'),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='popis'),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='kľúčové slová'),
        ),
        migrations.AddField(
            model_name='post',
            name='publised',
            field=models.BooleanField(default=True, verbose_name='publikovať'),
        ),
        migrations.AddField(
            model_name='post',
            name='publised_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publikovať'),
        ),
    ]
